easy_admin:
    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    entities:
        job:
            class: App\Entity\Job
            label: 'Jobs'
        contact:
            class: App\Entity\Contact
            label: 'Contact Request'
        skill_group:
            class: App\Entity\SkillGroup
            label: 'Skill Groups'
        skill_percent:
            class: App\Entity\SkillPercent
            label: 'Skill Percent'
        skill:
            class: App\Entity\Skill
            label: 'Skills'
            form:
                fields:
                    - name
                    - slug
                    - image_url
                    - skill_group
                    - { property: 'description', type: 'fos_ckeditor' }
        profile:
            class: App\Entity\Profile
            label: 'Profiles'
        user:
            class: App\Entity\User
            label: 'Users'
            list:
                fields:
                    - id
                    - username
                    - email
                    - profile
        sponsor:
            class: App\Entity\Sponsor
            label: 'Sponsor'
            list:
                fields:
                    - id
                    - name
                    - contact_name
                    - email
                    - { property: 'image', type: 'image', base_path: '%app.path.sponsor_images%' }
            show:
                fields:
                    - id
                    - name
                    - contact_name
                    - email
                    - description
                    - { property: 'image', type: 'image', base_path: '%app.path.sponsor_images%' }
                    - created_at
                    - updated_at
            form:
                fields:
                    - name
                    - contact_name
                    - email
                    - description
                    - { property: 'imageFile', type: 'vich_image' }
        meetup:
            class: App\Entity\MeetupEvent
            label: 'Meetup Events'
            form:
                fields:
                    - { type: 'section', label: 'Información General' }
                    - meetupId
                    - { property: 'scheduledAt', label: 'Fecha' }
                    - { property: 'title', label: 'Título' }
                    - { property: 'place', label: 'Lugar' }
                    - { property: 'description', type: 'fos_ckeditor', label: 'Descripción'}
                    - { property: 'attendingCount', label: 'Num. participantes'}
                    - { property: 'url', label: 'Url Meetup.com' }
                    - { property: 'imageFile', type: 'vich_image', label: 'Imagen de Portada'}
                    - { property: 'youtubeUrl', label: 'Url Youtube' }
                    - { property: 'twitterUrl', label: 'Url Twitter' }
                    - { property: 'facebookUrl', label: 'Url Facebook' }
                    - { property: 'slideUrl', label: 'Url Diapositivas' }
                    - { type: 'section', label: 'Información de Ponente' }
                    - { property: 'speaker', label: 'Ponente' }
                    - { property: 'speakerLinkedinUrl', label: 'Url Linkedin' }
                    - { property: 'speakerGitUrl', label: 'Url Git Personal' }
                    - { property: 'speakerTwitterUrl', label: 'Url Twitter' }
                    - { property: 'speakerFacebookUrl', label: 'Url Facebook' }
            list:
                fields:
                    - id
                    - scheduledAt
                    - title
                    - speaker
                    - { property: 'image', type: 'image', base_path: '%app.path.meetup_images%' }