vich_uploader:
    db_driver: orm

    mappings:
        sponsor_images:
            uri_prefix: '%app.path.sponsor_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.sponsor_images%'
