
version: '3.7'

networks:
  proxy:
    external:
      name: proxy
  internal:
    driver: bridge
    external: false

services:
  web:
    ports: []
    environment:
      - APACHE_RUN_USER=web
      - APP_ENV=prod
      - APP_DEBUG=0
      - WEB_ROOT=public
    labels:
      - "traefik.http.routers.whoami.rule=Host(`tres.phpmexico.mx`)"
    networks:
      - internal
      - proxy

  redis:
    networks:
      - internal
    labels:
      - traefik.enable=false

  db:
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - internal
    labels:
      - traefik.enable=false
