
version: '3.7'

networks:
  web:
    name: web
  internal:
    driver: bridge
    external: false

services:
  web:
    restart: always
    ports:
      - "80"
    environment:
      - APACHE_RUN_USER=web
      - APP_ENV=prod
      - APP_DEBUG=0
      - WEB_ROOT=public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.phpmxweb.entrypoints=websecure"
      - "traefik.http.routers.phpmxweb.tls.certresolver=phpmx"
      - "traefik.http.routers.phpmxweb.rule=Host(`www.phpmexico.mx`, `phpmexico.mx`)"
    networks:
      - internal
      - web

  redis:
    networks:
      - internal
    labels:
      - traefik.enable=false

  db:
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - internal
    labels:
      - traefik.enable=false
